force-app/main/default/objects/Child__c/Child__c.object-meta.xml
<CustomObject>
    <label>Child</label>
    <nameField>
        <label>Child Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Children</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Child__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <referenceTo>Parent__c</referenceTo>
    <relationshipLabel>Children</relationshipLabel>
    <relationshipName>Children</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Parent__c/Parent__c.object-meta.xml
<CustomObject>
    <label>Parent</label>
    <nameField>
        <label>Parent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Parent__c/fields/Total_Hours_in_related_child__c.field-meta.xml
<CustomField>
    <fullName>Total_Hours_in_related_child__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Hours in related children</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ChildTriggerrHandler.cls
public with sharing class ChildTriggerrHandler {

  // I will assume  that Hours field always changed 
  public static void updateTotalHoursOnParent(Map<Id,Child__c> newMap, Map<Id,Child__c> oldMap ){
    
    map<Id, decimal> totalHoursIncrementalChanges = new map<Id, decimal>();

    if(newMap != null){
      for( Child__c eachChild : newMap.values()){
        Id parentId = eachChild.Parent__c;
        if(parentId != null){
          if(totalHoursIncrementalChanges.containsKey(parentId)){
            totalHoursIncrementalChanges.put(parentId, totalHoursIncrementalChanges.get(parentId) + eachChild.Hours__c);
          }else{
            totalHoursIncrementalChanges.put(parentId, 0 + eachChild.Hours__c);
          }
        }
      }
    }

    if(oldMap != null){
      for( Child__c eachChild : oldMap.values()){
        Id parentId = eachChild.Parent__c;
        if(parentId != null){
          if(totalHoursIncrementalChanges.containsKey(parentId)){
            totalHoursIncrementalChanges.put(parentId, totalHoursIncrementalChanges.get(parentId) - eachChild.Hours__c);
          }else{
            totalHoursIncrementalChanges.put(parentId, 0 - eachChild.Hours__c);
          }
        }
      }
    }

    List<Parent__c> parentList;
    if(! totalHoursIncrementalChanges.keySet().isEmpty() ){
      parentList = [Select Id, Total_Hours_in_related_child__c from Parent__c where Id in : totalHoursIncrementalChanges.keySet()];

      for( Parent__c eachParent : parentList){
        eachParent.Total_Hours_in_related_child__c = eachParent.Total_Hours_in_related_child__c + totalHoursIncrementalChanges.get(eachParent.Id);
      }

      if(!parentList.isEmpty()){
        update parentList;
      }
    }
  }

}