force-app/main/default/objects/Child__c/Child__c.object-meta.xml
<CustomObject>
    <label>Child</label>
    <nameField>
        <label>Child Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Children</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Child__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <referenceTo>Parent__c</referenceTo>
    <relationshipLabel>Children</relationshipLabel>
    <relationshipName>Children</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Parent__c/Parent__c.object-meta.xml
<CustomObject>
    <label>Parent</label>
    <nameField>
        <label>Parent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Parent__c/fields/Total_Hours_in_related_child__c.field-meta.xml
<CustomField>
    <fullName>Total_Hours_in_related_child__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Hours in related children</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ChildTriggerHandler.cls
public with sharing class ChildTriggerHandler {
  
    public static void refreshParentHours(List<Child__c> oldChildList, List<Child__c> newChildList ){      
      system.debug('-----------------------------------------    refreshParentHours   BEGIN');
      Map<Id, Double> parentId_incrementalHoursMap = new Map<Id, Double>();

      //if there is oldChild updated I need to substract them from the incremental        
      if( oldChildList != null ){      
        system.debug('----------   there is old child: ' + oldChildList.size());  
        for(Child__c eachOldChild : oldChildList){
          Id parentId = eachOldChild.Parent__c;
          if( parentId != null ){   
            Double actualHours; 
            if(parentId_incrementalHoursMap.containsKey(parentId)){
              actualHours = parentId_incrementalHoursMap.get(parentId);
            }else{
              actualHours = 0;               
            }
            parentId_incrementalHoursMap.put(parentId, actualHours - eachOldChild.Hours__c);
          }
        }
      }

      //if the is newChild I need to add them from the incremental
      if( newChildList != null){     
        system.debug('----------   there is new child: ' + newChildList.size());    
        for(Child__c eachNewChild : newChildList){
          Id parentId = eachNewChild.Parent__c;
          if( parentId != null ){
            Double actualHours; 
            if(parentId_incrementalHoursMap.containsKey(parentId)){
              actualHours = parentId_incrementalHoursMap.get(parentId);
            }else{
              actualHours = 0;               
            }
            parentId_incrementalHoursMap.put(parentId, actualHours + eachNewChild.Hours__c);
          }
        }
      }
      
      //query the parents of the childList to update their total hour field
      if( !parentId_incrementalHoursMap.keySet().isEmpty() ){
        system.debug('----------   querying parents to update them'); 
        Map<Id, Parent__c> parentListToUpdate = new Map<Id, Parent__c>([Select Id, Total_Hours_in_related_child__c  from Parent__c where Id in : parentId_incrementalHoursMap.keySet()]);
        
        for(Parent__c eachParentToUpdate : parentListToUpdate.values()){
          eachParentToUpdate.Total_Hours_in_related_child__c  += parentId_incrementalHoursMap.get(eachParentToUpdate.Id);
        }       
        if( !parentListToUpdate.isEmpty() ){
          system.debug('-----------------------------------------    updating parent');
          update parentListToUpdate.values();
        }
      }
      system.debug('-----------------------------------------    refreshParentHours   END');
    }

}